"use client";

import { useQuery, useAction } from "convex/react";
import { api } from "@workspace/backend/convex/_generated/api";
import { SparklesIcon, LightbulbIcon, RefreshCwIcon, InboxIcon, ClockIcon, CheckCircle2Icon, AlertCircleIcon } from "lucide-react";
import { useState, useEffect } from "react";
import { cn } from "@workspace/ui/lib/utils";
import { Protect } from "@clerk/nextjs";
import { PremiumFeaturesOverlay } from "@/modules/billing/ui/components/premium-features-overlay";

export default function InsightsPage() {
    const stats = useQuery(api.private.conversations.getStats);
    const generateInsights = useAction(api.private.insights.generateOrgInsights);

    const [insights, setInsights] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const fetchInsights = async () => {
        setLoading(true);
        setError(null);
        try {
            const result = await generateInsights();
            setInsights(result);
        } catch (err: any) {
            setError(err.message || "Failed to generate insights.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchInsights();
    }, []);

    const totalCount = stats === undefined ? null : stats.total;
    const openCount = stats === undefined ? null : stats.unresolved;
    const resolvedCount = stats === undefined ? null : stats.resolved;
    const escalatedCount = stats === undefined ? null : stats.escalated;

    const renderMarkdown = (text: string) => {
        return text.split('\n').map((line, i) => {
            if (line.startsWith('### ')) return <h3 key={i} className="text-lg font-bold mt-4 mb-2 text-foreground">{line.replace('### ', '')}</h3>;
            if (line.startsWith('## ')) return <h2 key={i} className="text-xl font-bold mt-5 mb-3 text-foreground border-b pb-2">{line.replace('## ', '')}</h2>;
            if (line.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold mt-6 mb-4 text-foreground">{line.replace('# ', '')}</h1>;
            if (line.startsWith('- ')) {
                const content = line.replace('- ', '');
                return <li key={i} className="ml-6 list-disc mb-1 text-muted-foreground">{renderBold(content)}</li>;
            }
            if (line.startsWith('* ')) {
                const content = line.replace('* ', '');
                return <li key={i} className="ml-6 list-disc mb-1 text-muted-foreground">{renderBold(content)}</li>;
            }
            if (line.trim() === '') return <div key={i} className="h-2" />;

            return <p key={i} className="mb-2 text-muted-foreground leading-relaxed">{renderBold(line)}</p>;
        });
    };

    const renderBold = (text: string) => {
        const parts = text.split(/(\*\*.*?\*\*)/g);
        return parts.map((part, j) => {
            if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={j} className="font-semibold text-foreground">{part.slice(2, -2)}</strong>;
            }
            return part;
        });
    };

    const content = (
        <div className="flex flex-col flex-1 gap-8 max-w-5xl mx-auto w-full p-6">
            {/* ── Header ── */}
            <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                    <LightbulbIcon className="size-4 text-amber-500" />
                    <p className="text-xs text-amber-500 font-semibold tracking-wider uppercase">
                        Intelligence
                    </p>
                </div>
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <h1 className="text-3xl font-bold text-foreground tracking-tight">
                        AI Insights & Analytics
                    </h1>
                    <button
                        onClick={fetchInsights}
                        disabled={loading}
                        className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors shadow-sm disabled:opacity-50"
                    >
                        <RefreshCwIcon className={cn("size-4", loading && "animate-spin")} />
                        {loading ? "Analyzing Data..." : "Refresh Insights"}
                    </button>
                </div>
                <p className="text-sm text-muted-foreground mt-1 max-w-2xl">
                    Review statistics and receive actionable recommendations generated by AI based on your organization's recent conversations.
                </p>
            </div>

            {/* ── Light Stats ── */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="flex flex-col gap-1 p-5 rounded-2xl border border-border bg-card shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-muted-foreground">Total Messages</span>
                        <div className="size-8 rounded-lg bg-indigo-100 dark:bg-indigo-500/20 flex items-center justify-center">
                            <InboxIcon className="size-4 text-indigo-600 dark:text-indigo-400" />
                        </div>
                    </div>
                    <p className="text-3xl font-semibold tracking-tight">{totalCount !== null ? totalCount : "..."}</p>
                </div>
                <div className="flex flex-col gap-1 p-5 rounded-2xl border border-border bg-card shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-muted-foreground">Needs Action</span>
                        <div className="size-8 rounded-lg bg-amber-100 dark:bg-amber-500/20 flex items-center justify-center">
                            <ClockIcon className="size-4 text-amber-600 dark:text-amber-400" />
                        </div>
                    </div>
                    <p className="text-3xl font-semibold tracking-tight">{openCount !== null ? openCount : "..."}</p>
                </div>
                <div className="flex flex-col gap-1 p-5 rounded-2xl border border-border bg-card shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-muted-foreground">Resolved</span>
                        <div className="size-8 rounded-lg bg-emerald-100 dark:bg-emerald-500/20 flex items-center justify-center">
                            <CheckCircle2Icon className="size-4 text-emerald-600 dark:text-emerald-400" />
                        </div>
                    </div>
                    <p className="text-3xl font-semibold tracking-tight">{resolvedCount !== null ? resolvedCount : "..."}</p>
                </div>
                <div className="flex flex-col gap-1 p-5 rounded-2xl border border-border bg-card shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-muted-foreground">Escalated</span>
                        <div className="size-8 rounded-lg bg-red-100 dark:bg-red-500/20 flex items-center justify-center">
                            <AlertCircleIcon className="size-4 text-red-600 dark:text-red-400" />
                        </div>
                    </div>
                    <p className="text-3xl font-semibold tracking-tight">{escalatedCount !== null ? escalatedCount : "..."}</p>
                </div>
            </div>

            {/* ── AI Suggestions ── */}
            <div className="flex flex-col flex-1 rounded-2xl border border-border bg-card overflow-hidden shadow-sm">
                <div className="flex items-center gap-3 px-6 py-4 border-b border-border/50 bg-muted/30">
                    <SparklesIcon className="size-5 text-amber-500" />
                    <h2 className="text-lg font-semibold text-foreground">AI Intelligence Report</h2>
                </div>
                <div className="p-8">
                    {loading && !insights ? (
                        <div className="flex flex-col gap-5 animate-pulse max-w-3xl">
                            <div className="h-6 bg-muted/60 rounded w-1/4 mb-2"></div>
                            <div className="h-4 bg-muted/40 rounded w-full"></div>
                            <div className="h-4 bg-muted/40 rounded w-11/12"></div>
                            <div className="h-4 bg-muted/40 rounded w-4/5"></div>

                            <div className="h-6 bg-muted/60 rounded w-1/3 mt-6 mb-2"></div>
                            <div className="h-4 bg-muted/40 rounded w-full"></div>
                            <div className="h-4 bg-muted/40 rounded w-5/6"></div>
                        </div>
                    ) : error ? (
                        <div className="flex flex-col items-center justify-center py-12 text-center">
                            <div className="size-12 rounded-full bg-red-100 dark:bg-red-500/10 flex items-center justify-center mb-4">
                                <AlertCircleIcon className="size-6 text-red-600 dark:text-red-400" />
                            </div>
                            <h3 className="text-lg font-medium text-foreground mb-1">Analysis Failed</h3>
                            <p className="text-muted-foreground max-w-sm">{error}</p>
                        </div>
                    ) : insights ? (
                        <div className="max-w-4xl">
                            {renderMarkdown(insights)}
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center py-16 text-center">
                            <div className="size-16 rounded-full bg-amber-100 dark:bg-amber-500/10 flex items-center justify-center mb-4">
                                <LightbulbIcon className="size-8 text-amber-600 dark:text-amber-400" />
                            </div>
                            <h3 className="text-lg font-medium text-foreground mb-1">Ready for Analysis</h3>
                            <p className="text-muted-foreground max-w-sm">Click the refresh button to generate your first AI-driven insights report.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );

    return (
        <Protect
            condition={(has) => has({ plan: "pro" })}
            fallback={
                <div className="relative h-full w-full">
                    <div className="pointer-events-none select-none">
                        {content}
                    </div>
                    <PremiumFeaturesOverlay />
                </div>
            }
        >
            {content}
        </Protect>
    );
}
