import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// 1. Kept your monorepo global CSS import
import "@workspace/ui/globals.css";

// 2. Kept your custom <Providers> component
import { Providers } from "@/components/providers";

// 3. Added the <ClerkProvider> import from the docs
import { ClerkProvider } from "@clerk/nextjs";

// 4. Kept your font setup
const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

// 5. Added the Metadata export from the docs
export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 6. Kept your <html> tag
    <html lang="en" suppressHydrationWarning>
      {/* 7. Kept your <body> tag */}
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased `}
      >
        {/* 8. This is the new, merged wrapper structure.
            ClerkProvider is on the outside.
            Your custom Providers component (with themes/convex) is on the inside.
        */}
        <ClerkProvider>
          <Providers>{children}</Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
